#!/bin/zsh
# echo "Cloning ohmyzsh plugins..."
# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
# git clone https://github.com/paulirish/git-open.git ~/.oh-my-zsh/custom/plugins/git-open
# git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ~/.oh-my-zsh/custom/plugins/zsh-autocomplete

echo "Creating symlinks..."
ln -sfv ~/.dotfiles/gitconfig ~/.gitconfig
ln -sfv ~/.dotfiles/zshrc ~/.zshrc

# echo "Downloading Cyber Dotfiles"
# git clone https://github.com/ITV/.cyber-dotfiles.git ~/.cyber-dotfiles
# ~/.cyber-dotfiles/install.sh